### ISSUE TITLE
怎么同时使用淞和鹤的方案？

### ISSUE THREAD

**Issue by zhtdbobo** [kchen0x/rime-crane#13]
勾选了四个，只能使用鹤的功能，无法使用淞的功能
![image](https://github.com/kchen0x/rime-crane/assets/63108611/5552752c-23b8-4ab7-a834-deae58ff439e)
 
![w55lnwdy 2tn](https://github.com/kchen0x/rime-crane/assets/63108611/2207f8f9-872b-4d5f-9e68-2da5ca33357d)

**Comment by kchen0x** [comment]
为了避免后续的用户有相同的问题，补充一下：

```
switcher:
  caption: 「方案选单」
  hotkeys:
    - F4
    - Control+grave
    - Control+Shift+grave
```

可以使用上面三个快捷键进行方案切换。 grave 是键盘数字1 左边的 ` 键。
