### ISSUE TITLE
如何在音形下使用V引导输入符号

### ISSUE THREAD

**Issue by kimberlytor** [kchen0x/rime-crane#17]
请教下如何在音形下使用双拼和全拼可用的V引导输入符号功能？试过将双拼方案文件中的符号设置移植到xhup方案文件中并无效果。另外在xhup词库文件夹中看到了类似直通车的symbols词库，但是使用好像不如用V引导方便。
```
punctuator:
  full_shape:
    __include: default:/punctuator/full_shape  # 从 default.yaml 导入配置
  half_shape:
    __include: default:/punctuator/half_shape  # 从 default.yaml 导入配置
  symbols:
    __include: symbols_caps_v:/symbols         # 从 symbols_caps_v.yaml 导入配置
```
