### ISSUE TITLE
macOS下，如何更改Caps_Lock为中英切换，禁用shift

### ISSUE THREAD

**Issue by llllllizili** [kchen0x/rime-crane#22]
```yaml
ascii_composer:
  good_old_caps_lock: false  # true | false
  switch_key:
    Caps_Lock: commit_code
    Shift_L: noop 
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
```
以上配置未生效，大佬帮看下。或者，怎么禁用了Rime的英文模式，只要中文。谢谢🙏

**Comment by kchen0x** [comment]
你的意思是左右 Shift 什么都不干， Caps_Lock 使用系统默认的功能来切换输入法到系统英文状态吗？

**Comment by kchen0x** [comment]
这样的话调整点会比较多，因为我在配置文件中预设了多个默认使用Rime英文模式的软件，比如：iterm2、Terminal、XCode、Visual Code等终端和文本编码软件。这时需要通过左Shift切换为Rime中文迷失才能输入中文。
如果你把这个 `default.yaml` 配置调整：

```
# 中西文切换
#
# good_old_caps_lock:
# true   切换大写
# false  切换中英
# macOS 偏好设置的优先级更高，如果勾选【使用大写锁定键切换“ABC”输入法】则始终会切换输入法。
#
# 切换中英：
# 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后：
# commit_code  上屏原始的编码，然后切换到英文
# commit_text  上屏拼出的词句，然后切换到英文
# clear        清除未上屏内容，然后切换到英文
# inline_ascii 切换到临时英文模式，按回车上屏后回到中文状态
# noop         屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
ascii_composer:
  good_old_caps_lock: false  # true | false
  switch_key:
    Caps_Lock: noop       # commit_code | commit_text | clear
    Shift_L: noop          # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: noop         # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop
```

的话，那么可能会出现有些软件进入Rime英文模式你跳不出来的情况。
