### ISSUE TITLE
使用小鹤音形时，候选框的样式无法变更？

### ISSUE THREAD

**Issue by Harry-Wu** [kchen0x/rime-crane#23]
如下图，在候选不唯一时，可以看到候选之间不够紧凑，主要体现在：
- 多个候选之间有一条灰色竖线
- 编码提示使用了[]包裹，且与候选字/词间距较大
- 字体相对较大，无法更改
![image](https://github.com/kchen0x/rime-crane/assets/7098103/b01ec56d-f24c-4e4b-a84c-edec3b679ed5)

我尝试过修改xhup.schema.yaml文件内的“preset_color_schemes: # 凇鹤版小鹤双拼输入法皮肤” 字段，但候选框皮肤样式没有任何变化。请问一下是不是改动的文件不对，还是其他什么问题？

**Comment by kchen0x** [comment]
我手边没有windows不好测试，Windows应该是修改 /weasel.yaml 文件。
Windows下的皮肤问题比较多，辛苦自己多调一下了~
其实Windows下用小鹤自家的鹤形输入法也挺好的：
https://flypy.com

**Comment by Harry-Wu** [comment]
谢谢提醒，我在weasel.yaml中改小了字体、导角等设置，也确实看到候选框字体变小了，但是
- 候选词之间的竖条、以及编码提示的[]依然存在，不知道在哪里关
- 另外，我改成另一种皮肤，小鹤双拼和雾凇拼音都可以变更，但**小鹤音形**的皮肤一直是默认的，无法变更。见下面的演示：
https://github.com/kchen0x/rime-crane/assets/7098103/ddd88a40-d90c-4d5e-95de-a4fdfe995c42

**Comment by Harry-Wu** [comment]
小鹤音形模式下样式无法变更的原因在下面这个issue找到原因了：https://github.com/kchen0x/rime-crane/issues/14。去掉 xhup.schema.yaml内的皮肤设定后，皮肤就可以跟随系统设置了，并且竖条也没了。

现在只剩下编码提示两边的[]怎么去掉了。

**Comment by kchen0x** [comment]
`xhup.schema.yaml` 中100行这个部分是控制简码提示样式的：

```
short_hints:
  opencc_config: short_hints.json
  option_name: short_hints
  show_in_comment: true #作为注解在后面显示
  comment_format:
   - xform/^/〔/
   - xform/$/〕/
  tips: all
  # tags:
  #   - abc
  #   - tiger
  #   - tigress
  #   - xhup
    # - reverse_lookup
```

当然你也可以在64行把整个简码提示给关掉：

```
  filters:
    - simplifier
    - simplifier@simplification
    - simplifier@short_hints #滤镜
    - uniquifier
```
