### ISSUE TITLE
missing input schema: xhup  怎么音形不会出现

### ISSUE THREAD

**Issue by lishunyi123** [kchen0x/rime-crane#29]
日志报的错

**Comment by kchen0x** [comment]
你确定设置文件夹下有 xhup.schema.yaml 文件吗？

如果确定有的话，kill rime 的进程重新切换输入法试一下，有时候有些奇怪的缓存问题。

**Comment by lishunyi123** [comment]
> 你确定设置文件夹下有 xhup.schema.yaml 文件吗？
> 
> 如果确定有的话，kill rime 的进程重新切换输入法试一下，有时候有些奇怪的缓存问题。

确定是有那个yaml文件的，试了下还是出不来，使用步骤如下

- 鼠须管最新版
- git clone东风破
- 安装方案配置命令：bash rime-install kchen0x/rime-crane:others/recipes/full
- 点击“重新部署”
- Ctrl + ` 显示如下

1. 小鹤双拼
2. 雾凇拼音
3. xhup

- 即使把你的仓库clone下来按照命令软链，也还是一样的
- 选择xhup，鼠须管日志会看到错误 `missing input schema: xhup`

**Comment by kchen0x** [comment]
听上去非常的奇怪，请问一下你的操作系统环境信息。

**Comment by lishunyi123** [comment]
> 听上去非常的奇怪，请问一下你的操作系统环境信息。

- mac os 13.6
- 鼠须管最新版
- 还有一个问题想请教，我使用mac 的“聚焦搜索”「command + 空格」，只要是用鼠须管输入法，都会在“聚焦搜索”输入框里直接显示英文，不会出来鼠须管的中文待选框(无论什么方案），但是微信输入法/系统自带输入法就可以，不知道是什么原因呢

**Comment by kchen0x** [comment]
> 还有一个问题想请教，我使用mac 的“聚焦搜索”「command + 空格」，只要是用鼠须管输入法，都会在“聚焦搜索”输入框里直接显示英文，不会出来鼠须管的中文待选框(无论什么方案），但是微信输入法/系统自带输入法就可以，不知道是什么原因呢

这个是我有意为之，在切换到特定的软件：启动器、代码编辑器、终端等时默认切换成英文模式，需要通过左shift键切换到中文。

具体的控制在 `squirrel.yaml` 文件中：

```
# ascii_mode、inline、no_inline、vim_mode 等等设定
# 可参考 /Library/Input Methods/Squirrel.app/Contents/SharedSupport/squirrel.yaml
app_options:
  com.apple.Spotlight:
    ascii_mode: true
```
